### ISSUE TITLE
motion_category.number_motions

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend-coordination#103]
Replaces #31 

Payload:
```
{id: Id;}
```

**Comment by reiterl** [comment]
The OS3 comment + code are unclear. It seems like the comment doesn't match to the code.

**Comment by FinnStutzenstein** [comment]
Ok I try to write the expected behaviour here. If I write a term *in italics* This term is always refering to the given definition.

`motion_category.number_motions` is called with the id of ther _main category_ to number all motions. Categories itself build a tree with the `parent_id`/`children_ids` and `weight` fields. We are going to number all motions in all *affected categories*. The set of affected categories includes the main category and all categories in the tree of categories below it. These motions are called _affected motions_, since they all will be renamed. All affected motions are numbered in the order of `category_weight`.

I hope the three terms (main category, affected categories and affected motions) are clear.

First a precheck regarding *amendments* (A motion, which has a lead motion; relation `lead_motion_id`). For each affected motion is checked, if it is an amendment and if so, that the lead motion is also an affected motion. If this is not true for each affected motion, an error must be returned. [This is the original error message](https://github.com/OpenSlides/OpenSlides/blob/master/server/openslides/motions/numbering.py#L168).

Now onto the new `number` values to generage. I link to #24 to remember, that `number` is a string. We have multiple counters for the actual number-value (the actual integer), named *number_value* as in #24,  beginning at 1. For all non-amendments, there is one single counter, named _main counter_. There is also a counter for every amendment's lead motion, so the amendments of one lead motion can be numbered. For every affected motion, do:

- If the motion is not an amendment, the `number` consists of three parts `ABC`:
  - `A`: the prefix of the category of the motion
  - `B`: `" "` if `meeting/motions_amendments_prefix` is set, else `""`
  - `C`: Take the value of the main counter. Fill it with leading zeros until the `meeting/motions_number_min_digits` number of digits is reached. Increase the counter.
- If the motion is an amendment, the `number` consists of three parts `ABCD`:
  - `A`: The lead motions **new** number
  - `B`: `" "` if `meeting/motions_amendments_prefix` is set, else `""`
  - `C`: The value of `meeting/motions_amendments_prefix`
  - `D`: Take the value of the counter for the lead motion of the motion. Fill it with leading zeros until the `meeting/motions_number_min_digits` number of digits is reached. Increase the counter.

Check new numbers: if there is a non-affected motion in the meeting which has one of the fresh calculated numbers, [return a nice error](https://github.com/OpenSlides/OpenSlides/blob/master/server/openslides/motions/numbering.py#L230). This ensures, that all numbers are unique.

Set all new numbers.

This is the description what to be done. Algorithmically, there are some harder points:
- You have to number the motion-amendment-tree downwards, layer by layer. This is implicitly given by "`A`: The lead motions **new** number" for amendments: To number an amendment, you need the new number of the lead motion. So first you have to number all affected motions without a lead motion, than the first layer and so on. This is done in the old code by creating a layer-mapping (layer 0 is the root, layer 1 the one where each amendment has exactly one lead motion and so on.): https://github.com/OpenSlides/OpenSlides/blob/master/server/openslides/motions/numbering.py#L157 A map is returned mapping levels (from 0 to `max_amendment_level`) to a list of motions in these levels, so numbers can be generated level by level.
- Since we changing the motion `number`, we must have other number-changing code in mind. In #24, I used a special *number_value*. If this is saved in the Datastore, it must be updated here, too. If you choose another way to do it (see the motion create action for the problem with the *number_value*), it might be used here, too. E.g. in OS3 the *number_value* is saved as `identifier_number`: https://github.com/OpenSlides/OpenSlides/blob/master/server/openslides/motions/numbering.py#L267

Another note: Currently in OS4 every category has a prefix (the prefix was not required in OS3). This is a mistake. I'll remove the required-state for the prefix. This results in one more computation-step, I'll add later.

**Comment by FinnStutzenstein** [comment]
One rather complete example

Category tree (Syntax: `(<prefix>) <Name> <ID>`, empty parenthesis, if the category does not have a prefix):
```
(A) Allgemein 1
|-(B) Bildung 2
    |-() Sonstiges 3
    |   |-(K) Unter-Sonstiges 4 
    |-(S) Schule 5
```
Motions sorted into the category tree (`category_id` and `category_weight` are implicitly given by the tree). The names are just their DB ids. All motions do not have numbers yet. In parenthesis additional infomation is given for the motion
```
(A) Allgemein 1
|- 1
|- 2
|-(B) Bildung 2
    |-3 (lead_motion_id=7)
    |-4
    |-() Sonstiges 3
    |   |-5
    |   |-6
    |   |-(K) Unter-Sonstiges 4 
    |      |-7
    |      |-8
    |-(S) Schule 5
    |-9
    |-10
```

Now, we are numbering `(B) Bildung 2`. Settings:
`meeting/1/motions_number_with_blank=true`, `meeting/1/motions_number_min_digits=3`, `meeting/1/motions_amendments_prefix="X-"`. This is the result:
```
(A) Allgemein 1
|- 1
|- 2
|-(B) Bildung 2
    |-3 "K 004 X- 001"
    |-4 "B 001"
    |-() Sonstiges 3
    |   |-5 "B 002"
    |   |-6 "B 003"
    |   |-(K) Unter-Sonstiges 4 
    |      |-7 "K 004"
    |      |-8 "K 005"
    |-(S) Schule 5
    |-9 "S 006"
    |-10 "S 007"
```

# Failure case 1
Numbering `(B) Bildung 2` does not work:
```
(A) Allgemein 1
|- 1
|- 2
|-(B) Bildung 2
    |-3 (lead_motion_id=1) <-- Changed lead motion
    |-4
    |-() Sonstiges 3
    |   |-5
    |   |-6
    |   |-(K) Unter-Sonstiges 4 
    |      |-7
    |      |-8
    |-(S) Schule 5
    |-9
    |-10
```
The error should be something like `Amendment "3" cannot be numbered, because it's lead motion (1) is not in category B - Bildung or any subcategory.`

# Failure case 2
```
(A) Allgemein 1
|- 1 with number "B 002" <-- Changed
|- 2
|-(B) Bildung 2
    |-3 (lead_motion_id=7)
    |-4
    |-() Sonstiges 3
    |   |-5
    |   |-6
    |   |-(K) Unter-Sonstiges 4 
    |      |-7
    |      |-8
    |-(S) Schule 5
    |-9
    |-10
```
Should fail with an error like: `Numbering aborted because the motion identifier "B 002" already exists in category A - Allgemein.`
