### ISSUE TITLE
meeting.create_from_template

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend-coordination#112]
Payload
```
{
  committee_id: Id;
  name: string;
}
```
Raises an error, if the committee has no template meeting (`committee/template_meeting_id`). The meeting has to be cloned, and everything in it, too. This means, that a new meeting is created, with the `name` given from the payload. The every field form the template meeting is copied. Every model in the meeting is duplicated (every motion, topic, projector, ...) and assigned to the new meeting. At the end, there is a full clone of the old meeting. Especially every model gets new ids.

**Comment by jsangmeister** [comment]
Meetings can be marked as templates via `template_for_committee_id`. This action can be used to create a new meeting from such a template, which copies all settings from it.

Is anything else copied or did I miss something, @FinnStutzenstein?

**Comment by FinnStutzenstein** [comment]
I added some explainition in the top comment: Not only the meeting, but everything in it has to be cloned.
