### ISSUE TITLE
poll.create

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend-coordination#117]
Helper Interface for options to create:
```
Interface Option {
    // Exactly one of text and content_object_id must be given
    text: string;
    content_object_id: Fqid; // must be one of topic, user or motion and unique.

    // Only for type==analog, optional votes can be given
    Y?: decimal(6); // Y, YN, YNA mode
    N?: decimal(6); // N, YN mode
    A?: decimal(6); // YNA mode
}
```

Payload:
```
{
// Required
    title: string;
    type: string;
    pollmethod: string;

    meeting_id: Id;
    options: Option[]; // must have at least one entry.

// Optional
    content_object_id: Fqid;
    description: string;
    min_votes_amount: number;
    max_votes_amount: number;
    allow_multiple_votes_per_candidate: boolean;
    global_yes: boolean;
    global_no: boolean;
    global_abstain: boolean;
    onehundred_percent_base: string;
    majority_method: string;

// Only for non analog types
    entitled_group_ids: Id[];

// Only for type==analog
    publish_immediately: boolean;

// Only for type==analog, optional votes can be given
    votesvalid?: decimal(6);
    votesinvalid?: decimal(6);
    votescast?: decimal(6);
    amount_global_yes?: decimal(6);
    amount_global_no?: decimal(6);
    amount_global_abstain?: decimal(6);
}
```
If an analog poll with votes is given, the state is set to `finished` if at least one vote value is given. if `publish_immediately` is true and some vote value is given, the state is set to `published`. All options given are created as instances of the `option` model. If some options have values (for analog polls), `vote` objects have to be created, one for each option and vote value (Y, N, A).

The options must be unique in the way that each non-empty `text` and non-empty `content_object_id` can only exists once. The `option/weight` has to be set in the order the options are given in the payload.

**Comment by GabrielInTheWorld** [comment]
> // Exactly one of text and content_object_id must be given
>     text: string;
>     content_object_id: Fqid;

Why should exactly one text and content_object_id must be given? In case of a motion_poll, there is no text.

**Comment by FinnStutzenstein** [comment]
> Exactly one of text and content_object_id

So either `text` or `content_object_id`. Not both, not none.

**Comment by jsangmeister** [comment]
> Why should exactly one text and content_object_id must be given? In case of a motion_poll, there is no text.

To further answer you question: for motion polls, the underlying poll is the content object.
