### ISSUE TITLE
user.create_temporary

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend-coordination#134]
Create temporary user on meeting level. Payload:

    {
        // Required:
        meeting_id: Id
        username: string;

        // Optional:
        title: string;
        first_name: string;
        last_name: string;
        is_active: boolean;
        is_physical_person: boolean;
        default_password: string;
        about_me: HTML;
        gender: string;
        comment: HTML;
        number: string;
        structure_level: string;
        email: string;
        vote_weight: decimal;

        is_present_in_meeting_ids: Id[]; // can only contain the given meeting_id
        group_ids: Id[];  // will be written to group_$<meeting_id>_ids
        vote_delegations_from_ids: Id[]; // will be written into vote_delegations_$<meeting_id>_from_ids
    }

(@FinnStutzenstein please check and edit if needed. Done added default_password and group_ids)

**Comment by jsangmeister** [comment]
I think it doesn't really matter, but since it's less work for the backend people I vote for client ;)

**Comment by FinnStutzenstein** [comment]
Note: The payload changed: `is_committee` is now `is_physical_person` with default=true.

**Comment by FinnStutzenstein** [comment]
`vote_delegations_from_ids` is still missing as well as the entry in `meeting/user_ids`. @jsangmeister @reiterl It would be nice to have this action, one could create users to test other actions with.

**Comment by jsangmeister** [comment]
Is it restricted which user can assign their votes to which, like do they have to belong to the same meeting?

**Comment by jsangmeister** [comment]
For `meeting/user_ids` see meeting/user_ids. `vote_delegations_from_ids` done in https://github.com/OpenSlides/openslides-backend/pull/312

**Comment by jsangmeister** [comment]
The action should be working now (except `meeting/user_ids`)
