### ISSUE TITLE
user.update_temporary

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend-coordination#135]
Update of temporary user on meeting level. Payload (everything optional except id):

    {
        id: number;
        username: string;
        title: string;
        first_name: string;
        last_name: string;
        is_active: boolean;
        is_physical_person: boolean;
        default_password: string;
        about_me: HTML;
        gender: string;
        comment: HTML;
        number: string;
        structure_level: string;
        email: string;
        vote_weight: decimal;

        is_present_in_meeting_ids: Id[]; // can only contain the meeting_id of this user
        group_ids: Id[];  // will be written to group_$<meeting_id>_ids
        vote_delegations_from_ids: Id[];  // will be written to vote_delegations_$<meeting_id>_from_ids
    }

Needs `user.can_manage` permission in the meeting of this user.

**Comment by FinnStutzenstein** [comment]
Note: payload changed: `is_committee` -> `is_physical_person`.

**Comment by jsangmeister** [comment]
Is `vote_delegations_from_ids` missing here as well?

**Comment by FinnStutzenstein** [comment]
Yes, I think we waited for the discussion about writing is structured fields. Since create_temporary uses the plain `vote_delegations_from_ids`, we should use it here, too.

**Comment by jsangmeister** [comment]
Ok, adjusted payload.

**Comment by jsangmeister** [comment]
Done.
