### ISSUE TITLE
user.reset_password_to_default_temporary

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend-coordination#138]
Payload:
```
{id: Id;}
```

**Comment by reiterl** [comment]
What is the difference to `user.reset_password_to_default`?

**Comment by reiterl** [comment]
I think the difference is, that the code checks if the user is a temporary user, too.

**Comment by reiterl** [comment]
Opened https://github.com/OpenSlides/openslides-backend/pull/295 for this.

**Comment by jsangmeister** [comment]
> I think the difference is, that the code checks if the user is a temporary user, too.

Correct, the `temporary` actions can only be called on temporary users (=> meeting level), while the "normal" actions can be called on any user (=> organisation level)
