### ISSUE TITLE
user.set_password_temporary

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend-coordination#139]
Payload:
```
{
// Required
    id: Id;
    password: string;

// Optional
    set_as_default: boolean; // default false, if not given
}
```
Sets the password of the user given by `id` to `password`. If `set_as_default` is true, the `default_password` is also updated.

**Comment by reiterl** [comment]
Opened https://github.com/OpenSlides/openslides-backend/pull/293 for this.
