### ISSUE TITLE
user.update_self

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend-coordination#141]
Payload:
```
{
// Optional
    username: string;
    about_me: HTML;
    email: string;
}
```

**Comment by jsangmeister** [comment]
@reiterl See https://github.com/OpenSlides/openslides-backend/pull/270 for reference: for the `_self` methods, we use the current user_id, so id is not part of the payload. Please adjust the action and the tests and also throw an error if anonymous tries to update itself as shown in the other PR

**Comment by reiterl** [comment]
Opened PR https://github.com/OpenSlides/openslides-backend/pull/305 for this issue.
