### ISSUE TITLE
user.generate_new_password

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend-coordination#148]

**Comment by jsangmeister** [comment]
How should the password be generated? Length, (special) characters, etc... Does the auth service handle this or should the backend do it?

**Comment by FinnStutzenstein** [comment]
No, you can just do it. Generate a random string with a-z A-Z 0-9, 10 characters. We might rework this, if we have configurable password requirements - but for now, this is enough.

**Comment by reiterl** [comment]
Opened https://github.com/OpenSlides/openslides-backend/pull/292 for this.
