### ISSUE TITLE
personal_note.create

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend-coordination#152]
Payload:
```
{
// required
    content_object_id: Fqid;

// At least one has to be given
    star: boolean;
    note: HTML;
}
```
The `meeting_id` is set to the meeting id of the content object (this required the content object to be meeting-specific). Currently, only  `motion` is supported. The `user_id` is set to the request user, which must not be the anonymous. Fails, if there is already a personal note for the content object and the user (-> user_id` and `content_object_id` are unique together).

**Comment by reiterl** [comment]
Opened PR https://github.com/OpenSlides/openslides-backend/pull/303 for this.
