### ISSUE TITLE
meeting.unset_font

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend-coordination#155]
Payload:
```
{
    id: Id;
    place: string;
}
```
Unsets the `meeting/font_$<place>_id` relation.

**Comment by reiterl** [comment]
Opened https://github.com/OpenSlides/openslides-backend/pull/282 for this.
Better call it meeting.unset_font, because the font will unset from the meeting.

**Comment by jsangmeister** [comment]
> Better call it meeting.unset_font, because the font will unset from the meeting.

I agree. @FinnStutzenstein?

**Comment by jsangmeister** [comment]
Also, we should change the payload from `meeting_id` to `id` if we do that.

**Comment by FinnStutzenstein** [comment]
Ok, but we should be consistent and rename all 4 `set_logo`, `set_font`, and both unset variants. Is this ok?

**Comment by jsangmeister** [comment]
Yes, changed.

**Comment by FinnStutzenstein** [comment]
I guess here it is the same as in [unset_logo](https://github.com/OpenSlides/openslides-backend-coordination/issues/156#issuecomment-724652711). Not tested, but they are probably the same.

**Comment by normanjaeckel** [comment]
See https://github.com/OpenSlides/openslides-backend/pull/311

**Comment by jsangmeister** [comment]
Fixed.
