### ISSUE TITLE
meeting.unset_logo

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend-coordination#156]
Payload:
```
{
    id: Id;
    place: string;
}
```
Unsets the `meeting/logo_$<place>_id` relation.

**Comment by reiterl** [comment]
Opened https://github.com/OpenSlides/openslides-backend/pull/282 for this.

**Comment by jsangmeister** [comment]
Updated name and payload.

**Comment by FinnStutzenstein** [comment]
If I do this action with the example data ([important line](https://github.com/OpenSlides/OpenSlides/blob/openslides4-dev/docs/example-data.json#L320)):
```
[{action: "meeting.unset_logo", data: [{id: 1, place: "web_header"}]}]
```
this write request is created:
```
{'events': [{'type': 'update', 'fqid': FQId meeting/1, 'fields': {'logo_$web_header_id': None}}], 'information': {FQId meeting/1: ['Object updated']}, 'user_id': 1}
```
This is wrong in two ways:

1) `logo_$_id` is not modified -> Broken template field
2) There is no update for the mediafile 3 -> Broken relation

**Comment by jsangmeister** [comment]
@normanjaeckel can you look into this? I guess the issues lies in the general handling of structured relations and may hav to do with the underscore in the place. @FinnStutzenstein does this error occur with other places as well?

**Comment by normanjaeckel** [comment]
I can look at this but I would like to have a test for this in backend code so I can provide a fix on top.

**Comment by FinnStutzenstein** [comment]
> does this error occur with other places as well?

Not checked since all other structured relations are in users, which Is not tested in the client yet.

**Comment by jsangmeister** [comment]
No, I meant if you don't use `web_header` but instead another place

**Comment by FinnStutzenstein** [comment]
If you look [at the code](https://github.com/OpenSlides/openslides-backend/blob/master/openslides_backend/action/meeting/unset_font.py#L22) there is no direct relation handling at all. I'm not sure, if something generic should catch this behind the scenes, but as far as I remember you/norman did not want to impelement generic relations.

**Comment by jsangmeister** [comment]
Yes, the generic handling should catch this. But I will check
