### ISSUE TITLE
group.create

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend-coordination#158]
Payload:
```
{
// Required
    name: string;
    meeting_id: Id;

// Optional
    permissions: string[];
}
```
The default for `permissions` is `[]` and must be set by the backend. The values of `permission` must not be validated (except that is an array of strings) since the permission service will check, if each string is a valid permission - the backend does not have knowledge about available permissions.

**Comment by reiterl** [comment]
Opened https://github.com/OpenSlides/openslides-backend/pull/298 for this.
