### ISSUE TITLE
group.set_permission

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend-coordination#161]
Payload:
```
{
    id: Id;
    permission: string;
    set: boolean;
}
```
The strin `permission` is added (`set=True`) or removed (`set=False`) to the group without being checked [1]. If it is added and it already is in the array or removed and it wasn't there, no error must be returned.

[1] The permission service will check, if the string is a valid permission - the backend does not have knowledge about available permissions.

**Comment by reiterl** [comment]
Opened PR https://github.com/OpenSlides/openslides-backend/pull/304 for this issue.
