### ISSUE TITLE
Provide 'id's for bulk-creations

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend-coordination#162]
In the client are some bulk-actions (for example: the `motion-import.service.ts` needs those bulk-actions), which create multiple entries. In a next step these created entries are used to be assigned to, for example, a motion.
For this use-case it is useful, if the backend sends the `id` of a new created entry as response to the client. Otherwise the client has to find a new created entry in the whole viewmodellist of its collection. 
I think, that behaviour was already implemented in OS3.x, wasn't it?
Can it be implemented in the backend?

**Comment by FinnStutzenstein** [comment]
I requested it [here](https://github.com/OpenSlides/openslides-backend/issues/259), but it is still not implemented...
