### ISSUE TITLE
META: TODOs

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend-coordination#167]
Here, we can gather some TODOs with priorities and additional comments. The `TODO` label can be used to mark such issues.

- motion_category.number_motions: https://github.com/OpenSlides/openslides-backend-coordination/issues/103 (and https://github.com/OpenSlides/OpenSlides/pull/5728)
- https://github.com/OpenSlides/OpenSlides/pull/5723
- `motion.set_support_self`: https://github.com/OpenSlides/openslides-backend-coordination/issues/83
- Fix https://github.com/OpenSlides/openslides-backend-coordination/issues/33 (joshua)
  - It seems, that there are not tests, even for basic create. These should be added!
- Adjust the response from the backend service to the new interface: https://github.com/OpenSlides/openslides-backend/issues/261
- Check, if `motion.create` fulfills everything in https://github.com/OpenSlides/openslides-backend-coordination/wiki/Motions#creating-a-motion-motioncreate
  DONE: checked the motion.create code.
  DONE: created and last_modified must be calculated.
  Note: The part with "permission `can_manage`" can be skipped for now, but place a TODO there
  - https://github.com/OpenSlides/openslides-backend/issues/345 Create a submitter for the request user
- Check, if `motion.update` and `motion.update_metadata` works as described here: https://github.com/OpenSlides/openslides-backend-coordination/wiki/Motions#updating-a-motion-motionupdate-and-motionupdate_metadata
- `motion/last_modified` must be updated: https://github.com/OpenSlides/openslides-backend/issues/344
- `motion.set_state`, `motion.reset_state` and `motion.follow_recommendation`: The number updating code has to executed: https://github.com/OpenSlides/openslides-backend-coordination/wiki/Motions#updating-the-number
- `models.yml` in the main repo: meeting has many fields, which were configs in OS3 and sometimes renamed a bit. They all need to have defaults. The defaults can be found in the OS3 code looking into `server/openslides/*/config_variables.py`. There is a file for each app.
- #171 Prüfen Verhalten von Relationen und parallelen Aktionen in Bezug auf lockd_fields, tests mit Race-Conditions
- Voting: see https://github.com/OpenSlides/OpenSlides/pull/5698 for the restructure
  - the `generate_models.py` has to be adjusted to be able to handle the new case of generic template fields
  - all actions tagged as `Voting` have to be implemented (Difference to OS3: we do not differentiate between assigment and motion polls anymore, only the general actions have to be implemented)
  - these actions can (hopefully) be mostly ported from OS3. Also, in OS3 there are A LOT of tests for this, so it would be nice to port them, too. Maybe find an effective method for doing that automatically?
  - remove `allow_multiple_votes_per_candidate` from `models.yml`
- Implement the "point of order" feature from OS3 (not much documentation exists)...
- Organisation level:
  - Resources: https://github.com/OpenSlides/openslides-media-service/issues/13, https://github.com/OpenSlides/openslides-backend/issues/346, https://github.com/OpenSlides/openslides-backend-coordination/issues/170 and https://github.com/OpenSlides/openslides-backend-coordination/issues/169
  - user.merge_to_non_temporary: https://github.com/OpenSlides/openslides-backend-coordination/issues/140
    - It is mainly done, maybe some details are missing, but ready enough to start implementing
  - Meetings:
    - meeting.create (#109) and meeting.update(#110):
      - all settings are set in this action, that's why it's so verbose
      - Please check that all fields are up to date with the models.yml and write some tests
      - Check if all relations work
    - meeting.create: When a meeting is created, many other models has to also be created to setup the meeting. A list is given in #109 
    - meeting.create_from_template: https://github.com/OpenSlides/openslides-backend-coordination/issues/112

 
I tried to roughly put them in order from highest to lowest priority, but that's more of an estimate. At the end, everything has to be implemented.

And most importantly: assign issues to yourself if you start to work on them and preferably also mark it here, so there is no confusion what needs to be done still.

**Comment by jsangmeister** [comment]
I vote that we try to keep the comment above up to date and edit it if something changes. @FinnStutzenstein (or anyone else, if you notice something) feel free to add more things.

Also, the `Voting` actions have to be renamed/closed.

**Comment by FinnStutzenstein** [comment]
Moved to https://github.com/orgs/OpenSlides/projects/1
