### ISSUE TITLE
option.update

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend-coordination#168]
This is only possible, if the poll type is analog. Payload:
```
{
// Required
    id: Id;
// Optional.
    Y: number;
    N: number;
    A: number;
    publish_immediately: boolean;
}
```
Updating this option changes the associated `vote` objects for `Y`, `N` and `A` to the given values.

If the poll's state is created and at least one vote value is given (`Y`, `N` or `A`), the state must be set to finished. if additionally `publish_immediately` is given, the state must be set to published.

**Comment by GabrielInTheWorld** [comment]
Is there still a dedicated `option-repository`?

**Comment by FinnStutzenstein** [comment]
Yes, it should be.
