### ISSUE TITLE
meeting.set_logo

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend-coordination#22]

**Comment by FinnStutzenstein** [comment]
Attention: I changed the payload and behavior! Noone noticed, that with the old payload it was not possible to unset a mediafile as a logo. This is now possible, please read the new explaination below the payload.

**Comment by jsangmeister** [comment]
Updated name and payload.

**Comment by reiterl** [comment]
I think the payload should be more like this:
```
// Payload
id: Id; //meeting id
mediafile_id: Id;
place: string;
```

**Comment by jsangmeister** [comment]
Ok, updated.

**Comment by jsangmeister** [comment]
Done.
