### ISSUE TITLE
meeting.set_font

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend-coordination#23]

**Comment by normanjaeckel** [comment]
`place` should be renamed to `location` as used [in models.yml](https://github.com/OpenSlides/OpenSlides/blob/openslides4-dev/docs/models.yml#L678).

**Comment by FinnStutzenstein** [comment]
The models.yml is wrongly converted form the original models.txt. There, it was place: https://github.com/OpenSlides/OpenSlides/blob/e9fd1f108b0a21eaa98a83b0b84d7a914ef96a7f/docs/models.txt Also the client uses `place`. To keep consistent, I'll change the name in the models.yml.

**Comment by FinnStutzenstein** [comment]
Attention: I changed the payload and behavior! Noone noticed, that with the old payload it was not possible to unset a mediafile as a logo. This is now possible, please read the new explaination below the payload.

**Comment by jsangmeister** [comment]
Mmh, I don't like the renaming, but if you mean...

**Comment by normanjaeckel** [comment]
I also prefere `location`. See https://dict.leo.org/englisch-deutsch/location and https://dict.leo.org/englisch-deutsch/place

**Comment by jsangmeister** [comment]
I meant the renaming from `set_as_font` to `set_font` :D I have no opinion about place vs. location.

**Comment by jsangmeister** [comment]
Talked with @FinnStutzenstein and we will move this to meeting as well to keep it uniform. We'll keep the naming for `place` for now since it is also used in the client nad place is more fitting. If you really want to rename it, you'd have to go ahead and create PR's for backend and client where you change every usage.

**Comment by reiterl** [comment]
I think the payload of meeting.set_font should be:
```
// Payload
id: Id;
mediafile_id: Id;
place: string;

```

**Comment by jsangmeister** [comment]
Ok, updated.

**Comment by jsangmeister** [comment]
Done.
