### ISSUE TITLE
motion.update

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend-coordination#25]
Payload:
```
{
// Required
    id: Id;

// Optional
    title: string;
    number: string;
    text: HTML;
    reason: HTML;
    amendment_paragraphs: {
        [paragraph_number: number]: string
    };
    modified_final_version: HTML;
}
```

Implicit things to do when updating a motion:
- Set the timestamp `last_modified`
- If `meeting/motions_supporters_enable_autoremove` and `motion.state.allow_support` and from the permission service the additional information `clear_supporters` is true, clear all supporters of the motion.

**Comment by jsangmeister** [comment]
I guess here the same rules apply as in #24?

**Comment by jsangmeister** [comment]
> I guess here the same rules apply as in #24?

@FinnStutzenstein

**Comment by FinnStutzenstein** [comment]
Yes kind of: `lead_motion_id` and `statute_paragraph_id`  are read from the model and is not provided by the user as well as `text` nor `amendment_paragraphs` is required. But if one of them is given, it must been there previously. The reason may not bie given, but if it is and it is empty and `meeting/motions_reason_required` is true, it will be an error.

**Comment by reiterl** [comment]
Opened PR https://github.com/OpenSlides/openslides-backend/pull/338 for this.

**Comment by normanjaeckel** [comment]
Please also add origin, attachment_ids, supporters and workflow_id to the payload as discussed with @emanuelschuetze

**Comment by FinnStutzenstein** [comment]
@normanjaeckel the fields `attachment_ids`, `supporter_ids` and `workflow_id` are metadata and part of https://github.com/OpenSlides/openslides-backend-coordination/issues/65

they should not be updated here.

**Comment by jsangmeister** [comment]
> collapse both actions into one

I'm in favor of this. I didn't see from the start why we should have two seperate actions that basically do the same :D

**Comment by FinnStutzenstein** [comment]
Also my favorite

**Comment by normanjaeckel** [comment]
Please talk about this with @emanuelschuetze. His view came from the different client forms. For me it doesn't matter if some fields are there or not. Even merging both actions would be ok for me (although I think we should stay with the metadata action for all simple client clicks like changing state etc.)

**Comment by FinnStutzenstein** [comment]
Since [the client already sends two requests for updating](https://github.com/OpenSlides/openslides-client/blob/master/client/src/app/site/motions/modules/motion-detail/components/motion-detail/motion-detail.component.ts#L469) we should merge both actions.

> although I think we should stay with the metadata action for all simple client clicks like changing state etc.

Change state is a different action already due to more logic involved

But for the quick-selects in the client you are always able to send `{id: X, category_id: Y}` as a payload, so you can only change these fields.

Since this separation already got confused, I'll create an issue in the backend to merge these actions and reduce further misunderstandings and confusions.

**Comment by FinnStutzenstein** [comment]
Please move all discussions for `motion.update` to https://github.com/OpenSlides/openslides-backend/issues/487
