### ISSUE TITLE
motion_category.create

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend-coordination#54]

**Comment by GabrielInTheWorld** [comment]
> What's the status here?

If I will create a new motion-category with the following payload
```
[{'action': 'motion_category.create', 'data': [{'meeting_id': 1, 'name': 'helllo world', 'prefix': None, 'parent_id': None}]}]
```
the following error occurres:
```
Fehler: data.prefix must be string
```

Should "None" also be valid, because it's an optional value?

Do you need any more information about this?

**Comment by jsangmeister** [comment]
> Should "None" also be valid, because it's an optional value?

Yes, since it's a current change, the backend hasn't adapted it yet.

**Comment by FinnStutzenstein** [comment]
When updating a prefix sending `null` will left the prefix unchanged, but sending `""` should clear it. @jsangmeister is this the current behaviour of the backend handling `null` vs. `""`?

**Comment by jsangmeister** [comment]
No, normally the value is just delegated to the datastore, which means `null` would delete the field and `""` would set it to empty. But this can be adjusted on a per-action basis, of course.

**Comment by reiterl** [comment]
Opened PR https://github.com/OpenSlides/openslides-backend/pull/372 for making prefix optional.

**Comment by FinnStutzenstein** [comment]
> which means null would delete the field and "" would set it to empty.

Ah ok.  so "optional" really means undefined, so if the key is not there, it is not changed.

**Comment by GabrielInTheWorld** [comment]
What is the status here?
With the current master of the openslides-backend-repo (commit 951736ab0bf54b823f8d35881f150f6c78fb63d0) I get still the error:
`Fehler: data.prefix must be string.`

The payload I sent:
```
backend_1           | DEBUG:openslides_backend.http.application:Request contains JSON: [{'action': 'motion_category.create', 'data': [{'meeting_id': 1, 'name': 'Hello', 'prefix': None, 'parent_id': None}]}].
```

**Comment by FinnStutzenstein** [comment]
maybe open an issue directly there.

**Comment by reiterl** [comment]
The prefix must be a string, the message is correct. See payload.

**Comment by reiterl** [comment]
There exists the test motion_category/create.py: test_create_prefix_none for this. This test passes.

**Comment by jsangmeister** [comment]
I fixed this with https://github.com/OpenSlides/openslides-backend/pull/401. @GabrielInTheWorld please check if the error is resolved and given an update here.

**Comment by FinnStutzenstein** [comment]
I moved the discussion into https://github.com/OpenSlides/openslides-client/issues/95
