### ISSUE TITLE
mediafile.update

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-backend-coordination#63]

**Comment by reiterl** [comment]
Merge with https://github.com/OpenSlides/openslides-backend/pull/216

**Comment by FinnStutzenstein** [comment]
Updates of `access_group_ids` does not propagate with `inherited_access_group_ids` and `is_public` to children. E.g. in the example data: If I change the access groups of `mediafile/1` (a folder containing `mediafile/3`), `mediafile/3` is not updated.

**Comment by reiterl** [comment]
Opened PR ttps://github.com/OpenSlides/openslides-backend/pull/306 for this.

**Comment by jsangmeister** [comment]
Merged.
