### ISSUE TITLE
motion.update_metadata

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-backend-coordination#65]
some special cases are still missing

**Comment by FinnStutzenstein** [comment]
I found a missing case:
- We need to add `workflow_id` to the payload. If the workflow id is set and differentiates to the current state's workflow, the state has to be set to the first state of the new workflow. The recommendation has to be set to null. I've already changed the payload above.

**Comment by reiterl** [comment]
Opened PR https://github.com/OpenSlides/openslides-backend/pull/316 for this.

**Comment by jsangmeister** [comment]
Merged.

**Comment by normanjaeckel** [comment]
Remove attachments, workflow and origin from payload. This should be done in motion.update.

Supporters should stay.

**Comment by jsangmeister** [comment]
So supporters can be given for both actions? Seems inconsistent

**Comment by reiterl** [comment]
Opened PR https://github.com/OpenSlides/openslides-backend/pull/448. I cannot link it.

**Comment by FinnStutzenstein** [comment]
Lets discuss this in #25 and not splitted over all places.

**Comment by FinnStutzenstein** [comment]
Please move all discussions for `motion.update` (and former `motion.update_metadata`) to https://github.com/OpenSlides/openslides-backend/issues/487
