### ISSUE TITLE
motion_comment_section.delete

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend-coordination#96]
Payload:
```
 {id: Id;}
```
This must raise an error, if there are still comments in this section (`comment_ids` is not empty)

**Comment by FinnStutzenstein** [comment]
If I have a comment section with comments, the error message has to be improved. Currently: `You can not delete motion comment section with id 1, because you have to delete the related motion_comment first.`

See the error message in OS3: https://github.com/OpenSlides/OpenSlides/blob/master/server/openslides/motions/views.py#L1388

**Comment by jsangmeister** [comment]
Mmh, this is automatically handled by the cascade deletion, it would require extra work to customize the error messages for this. Are you sure it's needed? If you want, we can generally list the related ids, if that helps.

**Comment by FinnStutzenstein** [comment]
Yes. Most error messages will not be seen by users, but especially protected deletions are not catched by the client. Also, the error message must be descriptive: If I want to delete a comment section and one of 300 motions have a comment in this section, I need to know which one has the comment (Same for deleting motion_states..). This is the reason there is done a bit more logic in OS3 to provide good messages here.

**Comment by jsangmeister** [comment]
Ok. Will take care of this (although I do not know when...)

**Comment by jsangmeister** [comment]
Done.
